name: Tensorflow for Alpine linux

on:
  push:

jobs:
  builder:
    name: Run multi-stage build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        stage: ['base', 'build-base', 'compile', 'release']
        include:
          - stage: 'base'
            buildargs: ALPINE_PYTHON_IMAGE
          - stage: 'build-base'
            buildargs: BAZEL_VERSION, TF_VERSION, TF_BUILD_OPTIONS, LOCAL_RESOURCES
    env:
      ALPINE_PYTHON_IMAGE: python:3.7.6-alpine3.11
      BAZEL_VERSION: 0.29.1
      TF_VERSION: 2.1.0
      TF_BUILD_OPTIONS: --config opt --config=nocuda --config=noaws --config=nogcp --config=nohdfs --config=noignite --config=nokafka --config=nonccl
      LOCAL_RESOURCES: 4096,8.0,1.0
      PACKAGE_NAME: afsmnghr/alpine-tensorflow/alpine-tensorflow
    steps:

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Run ${{ matrix.stage }} stage
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ format('{0}:{1}-{2}', env.PACKAGE_NAME, env.TF_VERSION, matrix.stage) }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          buildoptions: --target ${{ matrix.stage }}
          buildargs: ${{ matrix.buildargs }}
          cache: true
