name: Tensorflow for Alpine linux

on:
  push:

jobs:
  builder:
    name: Run multi-stage build
    runs-on: ubuntu-latest
    env:
      ALPINE_PYTHON_IMAGE: python:3.7.6-alpine3.11
      TF_VERSION: 2.1.0
      PACKAGE_NAME: ${{ join(github.actor, '/', github.repository) }}
    steps:

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build and publish base alpine image to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ join(env.PACKAGE_NAME, ':', env.TF_VERSION, '-base') }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          buildoptions: '--target base'
          buildargs: ALPINE_PYTHON_IMAGE
          cache: true
