on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile TF for alpine linux
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Run multi-stage build
        run:
          using: 'docker'
          image: 'Dockerfile'
